"""Update models

Revision ID: 4f931e6aec9a
Revises: 1c877cb85e5f
Create Date: 2024-11-22 20:47:23.960199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f931e6aec9a'
down_revision: Union[str, None] = '1c877cb85e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_editorial_key', 'books', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('books_editorial_key', 'books', ['editorial'])
    # ### end Alembic commands ###
