"""Update models

Revision ID: 54e124e291c9
Revises: 113938babe78
Create Date: 2024-11-22 18:05:37.363025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54e124e291c9'
down_revision: Union[str, None] = '113938babe78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('editorial', sa.String(), nullable=False))
    op.drop_constraint('books_Editorial_key', 'books', type_='unique')
    op.create_unique_constraint(None, 'books', ['editorial'])
    op.drop_column('books', 'Editorial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('Editorial', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'books', type_='unique')
    op.create_unique_constraint('books_Editorial_key', 'books', ['Editorial'])
    op.drop_column('books', 'editorial')
    # ### end Alembic commands ###
